### ISSUE TITLE
How to configure RPC wallet for payments?

### ISSUE THREAD

**Issue by ArtRaptors** [Karbovanets/karbo-pool#2]
I have this error

> 2018-05-10 15:26:09 Error with send_transaction RPC request to wallet daemon
> {"code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect"}
> 
> 2018-05-10 15:26:09 Payments failed to send to {"amount":1100000000000,"address":"123"} { amount: 6900000000000, address: '123' }

**Comment by aivve** [comment]
https://github.com/seredat/karbowanec/wiki/Simplewallet-JSON-RPC-API
